SPACESHIP_PROMPT_ORDER=(
  #time           # Time stamps section
  user           # Username section
  dir            # Current directory section
  host           # Hostname section
  git            # Git section (git_branch + git_status)
  #hg             # Mercurial section (hg_branch  + hg_status)
  package        # Package version
  node           # Node.js section
  #bun            # Bun section
  #deno           # Deno section
  ruby           # Ruby section
  python         # Python section
  #elm            # Elm section
  #elixir         # Elixir section
  #xcode          # Xcode section
  #swift          # Swift section
  #golang         # Go section
  #perl           # Perl section
  php            # PHP section
  rust           # Rust section
  #haskell        # Haskell Stack section
  #scala          # Scala section
  #kotlin         # Kotlin section
  #java           # Java section
  lua            # Lua section
  dart           # Dart section
  #julia          # Julia section
  #crystal        # Crystal section
  docker         # Docker section
  docker_compose # Docker section
  #aws            # Amazon Web Services section
  #gcloud         # Google Cloud Platform section
  #azure          # Azure section
  venv           # virtualenv section
  conda          # conda virtualenv section
  #dotnet         # .NET section
  #ocaml          # OCaml section
  #vlang          # V section
  #zig            # Zig section
  #purescript     # PureScript section
  #erlang         # Erlang section
  #kubectl        # Kubectl context section
  #ansible        # Ansible section
  #terraform      # Terraform workspace section
  #pulumi         # Pulumi stack section
  #ibmcloud       # IBM Cloud section
  #nix_shell      # Nix shell
  #gnu_screen     # GNU Screen section
  exec_time      # Execution time
  async          # Async jobs indicator
  line_sep       # Line break
  #battery        # Battery level and status
  #jobs           # Background jobs indicator
  #exit_code      # Exit code section
  #sudo           # Sudo indicator
  char           # Prompt character
)

# CHAR - PROMPT
#SPACESHIP_CHAR_PREFIX=" "
#SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_SYMBOL="❯ "
SPACESHIP_CHAR_SYMBOL_SUCCESS="$SPACESHIP_CHAR_SYMBOL"
SPACESHIP_CHAR_SYMBOL_FAILURE="$SPACESHIP_CHAR_SYMBOL"
SPACESHIP_CHAR_SYMBOL_ROOT="$SPACESHIP_CHAR_SYMBOL"
SPACESHIP_CHAR_SYMBOL_SECONDARY="$SPACESHIP_CHAR_SYMBOL"
SPACESHIP_CHAR_COLOR_SUCCESS="#1793D1"
SPACESHIP_CHAR_COLOR_FAILURE="#FB4934"
SPACESHIP_CHAR_COLOR_SECONDARY=
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_PROMPT_SEPARATE_LINE=true
# SPACESHIP_CHAR_SYMBOL="" # warp terminal
# SPACESHIP_PROMPT_SEPARATE_LINE=false # warp terminal
SPACESHIP_PROMPT_ASYNC=false

# USER
SPACESHIP_USER_SHOW=true
SPACESHIP_USER_PREFIX="with "
SPACESHIP_USER_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_USER_COLOR="#FABD2F"
SPACESHIP_USER_COLOR_ROOT="#FB4934"

# DIR
SPACESHIP_DIR_SHOW=true
#SPACESHIP_DIR_PREFIX="in "
#SPACESHIP_DIR_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_DIR_TRUNC=2
SPACESHIP_DIR_TRUNC_PREFIX=".../"
SPACESHIP_DIR_TRUNC_REPO=true
SPACESHIP_DIR_COLOR="#98971A"
SPACESHIP_DIR_LOCK_SYMBOL=" "
SPACESHIP_DIR_LOCK_COLOR="#FB4934"

# HOST
SPACESHIP_HOST_SHOW=true
SPACESHIP_HOST_PREFIX="at "
SPACESHIP_HOST_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_HOST_COLOR="#98971A"

# GIT
SPACESHIP_GIT_SHOW=
SPACESHIP_GIT_ASYNC=
SPACESHIP_GIT_PREFIX=
SPACESHIP_GIT_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_GIT_SYMBOL=""
SPACESHIP_GIT_ORDER=(git_branch git_status)
# GIT BRANCH
SPACESHIP_GIT_BRANCH_SHOW=true
SPACESHIP_GIT_BRANCH_ASYNC=false
SPACESHIP_GIT_BRANCH_PREFIX="$SPACESHIP_GIT_SYMBOL"
SPACESHIP_GIT_BRANCH_SUFFIX=""
SPACESHIP_GIT_BRANCH_COLOR="#B16286"
# GIT STATUS
SPACESHIP_GIT_STATUS_SHOW=true
SPACESHIP_GIT_STATUS_ASYNC=true
SPACESHIP_GIT_STATUS_PREFIX=" ["
SPACESHIP_GIT_STATUS_SUFFIX="]"
SPACESHIP_GIT_STATUS_COLOR="#FB4934"
SPACESHIP_GIT_STATUS_UNTRACKED="?"
SPACESHIP_GIT_STATUS_ADDED="+"
SPACESHIP_GIT_STATUS_MODIFIED="!"
SPACESHIP_GIT_STATUS_RENAMED="»"
SPACESHIP_GIT_STATUS_DELETED="✘"
SPACESHIP_GIT_STATUS_STASHED="S"
SPACESHIP_GIT_STATUS_UNMERGED=""
SPACESHIP_GIT_STATUS_AHEAD="⇡"
SPACESHIP_GIT_STATUS_BEHIND="⇣"
SPACESHIP_GIT_STATUS_DIVERGED="⇕"

# PACKAGE
SPACESHIP_PACKAGE_SHOW=true
SPACESHIP_PACKAGE_ASYNC=true
SPACESHIP_PACKAGE_SHOW_PRIVATE=false
#SPACESHIP_PACKAGE_PREFIX="is·"
SPACESHIP_PACKAGE_PREFIX="is "
SPACESHIP_PACKAGE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_PACKAGE_SYMBOL="📦·"
SPACESHIP_PACKAGE_SYMBOL="📦 "
SPACESHIP_PACKAGE_COLOR="#FB4934"

# NODE
SPACESHIP_NODE_SHOW=true
SPACESHIP_NODE_ASYNC=true
SPACESHIP_NODE_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_NODE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_NODE_SYMBOL="󰎙 "
SPACESHIP_NODE_COLOR="#75AC64"
SPACESHIP_NODE_DEFAULT_VERSION=""

# RUBY
# RUBY
SPACESHIP_RUBY_SHOW=true
SPACESHIP_RUBY_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_RUBY_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_RUBY_SYMBOL="💎 "
SPACESHIP_RUBY_SYMBOL=" "
SPACESHIP_RUBY_COLOR="#D30001"

# PYTHON
SPACESHIP_PYTHON_SHOW=true
SPACESHIP_PYTHON_ASYNC=true
SPACESHIP_PYTHON_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_PYTHON_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_PYTHON_SYMBOL=" "
SPACESHIP_PYTHON_COLOR="#3570A0"
# VENV
SPACESHIP_VENV_SHOW=true
SPACESHIP_VENV_ASYNC=false
SPACESHIP_VENV_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_VENV_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_VENV_SYMBOL="(.venv) · "
SPACESHIP_VENV_COLOR="#458588"
# CONDA
SPACESHIP_CONDA_SHOW=true
SPACESHIP_CONDA_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_CONDA_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_CONDA_SYMBOL="🅒·"
SPACESHIP_CONDA_COLOR="#458588"
SPACESHIP_CONDA_VERBOSE=true

# PHP
SPACESHIP_PHP_SHOW=true
SPACESHIP_PHP_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_PHP_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_PHP_SYMBOL="🐘 "
SPACESHIP_PHP_SYMBOL=" "
SPACEHIP_PHP_COLOR="#777BB3"

# RUST
SPACESHIP_RUST_SHOW=false
SPACESHIP_RUST_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_RUST_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
#SPACESHIP_RUST_SYMBOL="𝗥 "
SPACESHIP_RUST_SYMBOL=" "
SPACESHIP_RUST_COLOR="#EB4601"

# LUA
SPACESHIP_LUA_SHOW=true
SPACESHIP_LUA_ASYNC=true
SPACESHIP_LUA_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_LUA_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_LUA_SYMBOL="󰢱 "
SPACESHIP_LUA_COLOR="#00007C"

# DART
SPACESHIP_DART_SHOW=true
SPACESHIP_DART_ASYNC=true
SPACESHIP_DART_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
SPACESHIP_DART_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_DART_SYMBOL=" "
SPACESHIP_DART_COLOR="#2AB1EE"

# DOCKER
SPACESHIP_DOCKER_SHOW=true
SPACESHIP_DOCKER_ASYNC=true
SPACESHIP_DOCKER_PREFIX="on "	
SPACESHIP_DOCKER_SUFFIX=$SPACESHIP_PROMPT_DEFAULT_SUFFIX
SPACESHIP_DOCKER_SYMBOL=" "
SPACESHIP_DOCKER_COLOR="#2391E5"
SPACESHIP_DOCKER_VERBOSE=false
# DOCKER COMPOSE
SPACESHIP_DOCKER_COMPOSE_SHOW=true
SPACESHIP_DOCKER_COMPOSE_ASYNC=true
SPACESHIP_DOCKER_COMPOSE_PREFIX=""
SPACESHIP_DOCKER_COMPOSE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_DOCKER_COMPOSE_SYMBOL="󰡨 "
SPACESHIP_DOCKER_COMPOSE_COLOR="#2391E5"
SPACESHIP_DOCKER_COMPOSE_COLOR_UP=green
SPACESHIP_DOCKER_COMPOSE_COLOR_DOWN=red
SPACESHIP_DOCKER_COMPOSE_COLOR_PAUSED=yellow

# EXECUTION_TIME
SPACESHIP_EXEC_TIME_SHOW=true
SPACESHIP_EXEC_TIME_PREFIX="took "
SPACESHIP_EXEC_TIME_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
SPACESHIP_EXEC_TIME_COLOR="#FABD2F"
SPACESHIP_EXEC_TIME_ELAPSED=2
SPACESHIP_EXEC_TIME_PRECISION=1

# ASYNC
SPACESHIP_ASYNC_SHOW=false
SPACESHIP_ASYNC_SHOW_COUNT=false
SPACESHIP_ASYNC_PREFIX=""
SPACESHIP_ASYNC_SUFFIX=""
SPACESHIP_ASYNC_SYMBOL="" # remove the tree dots end of lines
SPACESHIP_ASYNC_COLOR=gray
