#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#----------Monitor----------#
bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 0

#----------DUPLICATE PROGRAM AUTOSTART----------
killall sxhkd 2>/dev/null
killall polybar 2>/dev/null
killall -qw picom 2>/dev/null
killall -q dunst 2>/dev/null
killall nm-applet 2>/dev/null
killall -q udiskie 2>/dev/null
killall greenclip 2>/dev/null
# killall paperview 2>/dev/null
killall redshift 2>/dev/null # Or use redshift &
killall flameshot 2>/dev/null
killall blueman-applet 2>/dev/null

#----------AUTOSTART----------
wmname LG3D &
xset dpms 0 0 0 #Disable 10 minutes black screen
sh $HOME/.config/polybar/scripts/fake1080p.sh
sh $HOME/.config/polybar/launch.sh
sxhkd &
sh ~/.fehbg &
picom -b &
bash ~/.config/dunst/load.sh # Load dunst configuration
bash ~/.config/dunst/play.sh
redshift &
nm-applet &
blueman-applet &
xsetroot -cursor_name left_ptr &
greenclip daemon &
udiskie -t &
flameshot &
libinput-gestures-setup start & # para gestos del touchpad
#paperview ~/Pictures/Gifs/bmp/sakura 5 0 0 1920 1080  ~/Pictures/Gifs/bmp/daft 5 1920 0 1920 1080 &
#paperview ~/Pictures/Gifs/bmp/sakura 5 0 0 1920 1080  ~/Pictures/Gifs/bmp/ae 5 1920 0 1920 1080 &
#setxkbmap -layout us,us -variant altgr-intl,dvorak-intl -option grp:alt_shift_toggle &
#setxkbmap -layout us -variant altgr-intl &

#----------ListProviders----------#
GPU=`xrandr --listproviders | grep "Provider 1"`
if [[ $GPU ]]; then
	xrandr --listproviders 1 0
	DRI_PRIME=1
fi

#----------MONITORS----------#
bspc config border_radius        	10
bspc config border_width         	2
bspc config window_gap           	5
bspc config top_padding          	25
# bspc config top_padding          	0
bspc config bottom_padding       	0
bspc config left_padding         	0
bspc config right_padding        	0
bspc config single_monocle       	false

bspc config split_ratio  	 	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle 	 	true
bspc config focus_by_distance    	true
#bspc config pointer_follows_focus true
bspc config focus_follows_pointer 	true
bspc config history_aware_focus		true
bspc config remove_disabled_monitors	true
bspc config merge_overlapping_monitors	true
bspc config pointer_modifier		mod4
bspc config pointer_action1		move
bspc config pointer_action2		resize_side
bspc config pointer_action3		resize_corner
# monitors
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

#----------BSPWM Coloring----------#
bspc config normal_border_color		"#3C3836"
bspc config active_border_color		"#3C3836"
bspc config focused_border_color	"#458588"
bspc config presel_feedback_color	"#458588"
bspc config urgent_border_color		"#CC241D"

# polybar hidden when full screen for vlc, youtube, mpv ...
# find out the name of your monitor with xrandr
# look variable output video with xrandr command
xdo below -t (xdo id -n root) $(xdo id -a polybar-main-eDP-1)
xdo below -t (xdo id -n root) $(xdo id -a polybar-secondary-HDMI-1)


bspc rule -a Zathura state=tiled follow=on

#bspc rule -a Code desktop='^2' #open VSCcode on workspace 2
bspc rule -a Code follow=on
bspc rule -a Soffice desktop='^4' #open any libreoffice suit, move to workspace 6
#bspc rule -a firefox desktop='^6' #open firefox, move to desktop 6
bspc rule -a pomotroid state=floating rectangle=600+503+145

bspc rule -a Font-manager state=floating follow=on center=true
bspc rule -a gnome-calculator state=floating
bspc rule -a android-studio state=floating follow=on center=true
bspc rule -a Gpick state=floating
bspc rule -a intellij-idea-ultimate-edition state=floating follow=on center=true
